name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
      - "feature/*"
      - "hotfix/*"

  pull_request:
    branches:
      - main
      - develop

jobs:
  build-test-security:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Perfulandia-Backend-Natalia

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # JAVA
      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Dar permisos a Maven Wrapper
        run: chmod +x mvnw

      # BUILD Y TEST
      - name: Build & Test
        run: ./mvnw clean verify

      # DOCKER
      - name: Build Docker Image
        run: docker build -t perfulandia-backend .

      # NODE PARA SNYK
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar Snyk
        run: npm install -g snyk

      - name: Snyk Scan
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk test --severity-threshold=critical || true

      # SONARQUBE CLOUD
      - name: SonarQube Cloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./mvnw sonar:sonar \
          -Dsonar.projectKey=EVALUACION_1_INGENIERIA_DEVOPS_002D_OLS \
          -Dsonar.organization=natalia000000 \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.token=${SONAR_TOKEN}

      # QUALITY GATE
      - name: Quality Gate
        uses: SonarSource/sonarqube-quality-gate-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Finalizado
        run: echo "CI/CD ejecutado correctamente."
